[supervisord]
nodaemon=true

# Pull in any drop-in programs (e.g. mount-scratch, written by the Ansible
# `just mount-scratch` step) so they run on every container start.
[include]
files = /etc/supervisord.d/*.ini

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
stdout_logfile=/var/log/sshd.out
stderr_logfile=/var/log/sshd.err
